version: '3'
services:
  web:
    image: php:7.3-apache
    depends_on:
      - db
    volumes:
      - .:/var/www/html
    ports: 
      - 8484:80
  db:
    image: mysql:5.7
    user: "1000:50"
    volumes:
      - ./db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: pass
  phpMyAdmin:
    image: phpmyadmin/phpmyadmin:4.6.6-1
    depends_on:
      - db
    ports: 
      - 8080:80